linters:
  presets:
    - bugs
    - complexity
    - error
    - format
    - import
    - metalinter
    - performance
    - style
    - test
    - unused
  disable:
    - depguard
    - prealloc
    - godot
    - lll
    - wsl
  fast: true

issues:
  exclude-rules:
    # disable funlen for test funcs
    - path: _test.go
      linters:
        - funlen
        - dupl
        - maintidx
        - cyclop
